/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package upm;

import java.awt.Color;
import java.awt.Desktop;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Kai_Tang
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    DefaultTableModel dm;
    
    public Home() {
        initComponents();
        
        CreateColums();
        
    }
    
    private void CreateColums()
    {
        dm=(DefaultTableModel) jTable1.getModel();
        jTable1.setBackground(Color.WHITE);
        dm.addColumn("Title");
        dm.addColumn("User ID");
        dm.addColumn("URL");
        dm.addColumn("Password");
    }
    
    private void filter(String query)
    {
        TableRowSorter<DefaultTableModel> tr= new TableRowSorter<DefaultTableModel>(dm);
        jTable1.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(query));
    }
    
    private void Polulate(String title, String userID, String url, String pass)
    {
        String[] rowData={title,userID,url,pass};
        dm.addRow(rowData);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        jHomePanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        checkbox = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        accountName = new javax.swing.JTextField();
        accountID = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        accountURL = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        cancel1 = new javax.swing.JButton();
        jUser = new javax.swing.JButton();
        jPass = new javax.swing.JButton();
        jLaunch = new javax.swing.JButton();
        jSetting = new javax.swing.JButton();
        jHelp = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        filterTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        Change_Pass = new javax.swing.JMenuItem();
        jLock = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jExit = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jHomePanel.setBackground(new java.awt.Color(255, 255, 255));
        jHomePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(118, 123, 124));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("GB18030 Bitmap", 0, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Account");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 50, 66, -1));

        jLabel12.setFont(new java.awt.Font("GB18030 Bitmap", 0, 13)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("User ID");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 94, 63, -1));

        jLabel13.setFont(new java.awt.Font("GB18030 Bitmap", 0, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Password");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 135, 72, -1));

        checkbox.setFont(new java.awt.Font("GB18030 Bitmap", 0, 10)); // NOI18N
        checkbox.setText("show Password");
        checkbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxActionPerformed(evt);
            }
        });
        jPanel4.add(checkbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 167, -1, 17));

        jLabel14.setFont(new java.awt.Font("GB18030 Bitmap", 0, 13)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("URL");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 205, 33, -1));
        jPanel4.add(accountName, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 47, 186, -1));

        accountID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountIDActionPerformed(evt);
            }
        });
        jPanel4.add(accountID, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 91, 186, -1));

        passwordField.setColumns(15);
        jPanel4.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 135, 186, -1));
        jPanel4.add(accountURL, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 202, 186, -1));

        add.setBackground(new java.awt.Color(255, 255, 255));
        add.setFont(new java.awt.Font("GB18030 Bitmap", 0, 13)); // NOI18N
        add.setText("Add");
        add.setToolTipText("");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel4.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 239, 67, -1));

        edit.setBackground(new java.awt.Color(255, 255, 255));
        edit.setFont(new java.awt.Font("GB18030 Bitmap", 0, 13)); // NOI18N
        edit.setText("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        jPanel4.add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 239, 72, -1));

        cancel1.setBackground(new java.awt.Color(255, 255, 255));
        cancel1.setFont(new java.awt.Font("GB18030 Bitmap", 0, 13)); // NOI18N
        cancel1.setText("Delete");
        cancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel1ActionPerformed(evt);
            }
        });
        jPanel4.add(cancel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, -1));

        jHomePanel.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 0, 270, 328));

        jUser.setBackground(new java.awt.Color(255, 255, 255));
        jUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/upm/copyusername.png"))); // NOI18N
        jUser.setMaximumSize(new java.awt.Dimension(59, 55));
        jUser.setMinimumSize(new java.awt.Dimension(59, 55));
        jUser.setPreferredSize(new java.awt.Dimension(57, 55));
        jUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUserActionPerformed(evt);
            }
        });
        jHomePanel.add(jUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 49, 50));

        jPass.setBackground(new java.awt.Color(255, 255, 255));
        jPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/upm/copypassword.png"))); // NOI18N
        jPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPassActionPerformed(evt);
            }
        });
        jHomePanel.add(jPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 49, 53));

        jLaunch.setBackground(new java.awt.Color(255, 255, 255));
        jLaunch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/upm/launch2.png"))); // NOI18N
        jLaunch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLaunchActionPerformed(evt);
            }
        });
        jHomePanel.add(jLaunch, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 0, 51, -1));

        jSetting.setBackground(new java.awt.Color(255, 255, 255));
        jSetting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/upm/option.png"))); // NOI18N
        jSetting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSettingActionPerformed(evt);
            }
        });
        jHomePanel.add(jSetting, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 0, 50, -1));

        jHelp.setBackground(new java.awt.Color(255, 255, 255));
        jHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/upm/help.png"))); // NOI18N
        jHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHelpActionPerformed(evt);
            }
        });
        jHomePanel.add(jHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 0, 50, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/upm/seach.png"))); // NOI18N
        jHomePanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 91, -1, -1));

        filterTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterTxtActionPerformed(evt);
            }
        });
        filterTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                filterTxtKeyReleased(evt);
            }
        });
        jHomePanel.add(filterTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 93, 263, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setSelectionBackground(new java.awt.Color(204, 204, 204));
        jTable1.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jHomePanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 137, 340, 190));

        jLabel4.setFont(new java.awt.Font("GB18030 Bitmap", 0, 13)); // NOI18N
        jLabel4.setText(" User");
        jHomePanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, 20));

        jLabel5.setFont(new java.awt.Font("GB18030 Bitmap", 0, 13)); // NOI18N
        jLabel5.setText(" Pass");
        jHomePanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 60, 20));

        jLabel6.setFont(new java.awt.Font("GB18030 Bitmap", 0, 13)); // NOI18N
        jLabel6.setText(" Launch");
        jHomePanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, 20));

        jLabel7.setFont(new java.awt.Font("GB18030 Bitmap", 0, 13)); // NOI18N
        jLabel7.setText("Setting");
        jHomePanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, -1, 20));

        jLabel8.setFont(new java.awt.Font("GB18030 Bitmap", 0, 13)); // NOI18N
        jLabel8.setText("Help");
        jHomePanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 40, 20));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jHomePanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 380, 10));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jHomePanel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 380, 10));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/upm/reset.jpg"))); // NOI18N
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jHomePanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 30, 30));

        jMenu4.setText("Account");
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Change Security Question");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        Change_Pass.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        Change_Pass.setText("Change Password");
        Change_Pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Change_PassActionPerformed(evt);
            }
        });
        jMenu4.add(Change_Pass);

        jLock.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, 0));
        jLock.setText("Lock Program");
        jLock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLockActionPerformed(evt);
            }
        });
        jMenu4.add(jLock);

        jMenuBar2.add(jMenu4);

        jMenu5.setText("Exit");
        jMenu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu5ActionPerformed(evt);
            }
        });

        jExit.setText("Exit");
        jExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitActionPerformed(evt);
            }
        });
        jMenu5.add(jExit);

        jMenuBar2.add(jMenu5);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jHomePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jHomePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUserActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,"Copy username success","Notification",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jUserActionPerformed

    private void jPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPassActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,"Copy password success","Notification",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jPassActionPerformed

    private void jLaunchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLaunchActionPerformed
        // TODO add your handling code here:
        try
        {
            Desktop.getDesktop().browse(new URL("http://google.com").toURI());

        } catch (MalformedURLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        } catch (URISyntaxException | IOException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLaunchActionPerformed

    private void jSettingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSettingActionPerformed
        // TODO add your handling code here:
        settingPage set = new settingPage();
        set.setVisible(true);
    }//GEN-LAST:event_jSettingActionPerformed

    private void jHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHelpActionPerformed
        // TODO add your handling code here:
        try
        {
            Desktop.getDesktop().browse(new URL("http://upm.sourceforge.net/upm_swing_userguide.html").toURI());

        } catch (URISyntaxException | IOException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jHelpActionPerformed

    private void filterTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterTxtActionPerformed
        // TODO add your handling code here:
        String query=filterTxt.getText().toLowerCase();
        filter(query);
    }//GEN-LAST:event_filterTxtActionPerformed

    private void filterTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filterTxtKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_filterTxtKeyReleased

    private void checkboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxActionPerformed
        // TODO add your handling code here:
        if(checkbox.isSelected())
        {
            passwordField.setEchoChar((char)0);
        }
        else
        {
            passwordField.setEchoChar('*');
        }
    }//GEN-LAST:event_checkboxActionPerformed

    private void accountIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accountIDActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
       
        Polulate(accountName.getText(),accountURL.getText(),accountID.getText(),passwordField.getText());
        accountName.setText("");
        accountID.setText("");
        accountURL.setText("");
        passwordField.setText("");
       
        JOptionPane.showMessageDialog(this,"Add account suceess","Notification",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_addActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        
        dm.setValueAt(accountName.getText(),jTable1.getSelectedRow(),0);
        dm.setValueAt(accountURL.getText(),jTable1.getSelectedRow(),1);
        dm.setValueAt(accountID.getText(),jTable1.getSelectedRow(),2);
        dm.setValueAt(passwordField.getText(),jTable1.getSelectedRow(),3);

        accountName.setText("");
        accountID.setText("");
        accountURL.setText("");
        passwordField.setText("");
        
        JOptionPane.showMessageDialog(this,"Edit success!.","Edit",JOptionPane.INFORMATION_MESSAGE);


    }//GEN-LAST:event_editActionPerformed

    private void cancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel1ActionPerformed
        // TODO add your handling code here:
      int reply=  JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this account? \n This action cannot be reveted.", "Select an Option...",JOptionPane.YES_NO_OPTION);
       if (reply == JOptionPane.YES_OPTION) {
      dm.removeRow(jTable1.getSelectedRow());
       }
    }//GEN-LAST:event_cancel1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        accountName.setText(jTable1.getValueAt(jTable1.getSelectedRow(),0).toString());  
        accountURL.setText(jTable1.getValueAt(jTable1.getSelectedRow(),1).toString());  
        accountID.setText(jTable1.getValueAt(jTable1.getSelectedRow(),2).toString());  
        passwordField.setText(jTable1.getValueAt(jTable1.getSelectedRow(),3).toString());  
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        filterTxt.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu5ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jMenu5ActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenu4ActionPerformed

    private void Change_PassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Change_PassActionPerformed
        // TODO add your handling code here:
        this.dispose();
        forgotPassword forgot = new forgotPassword();
        forgot.setVisible(true);
      
    }//GEN-LAST:event_Change_PassActionPerformed

    private void jLockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLockActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_jLockActionPerformed

    private void jExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jExitActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        securityQuestion sec= new securityQuestion();
        sec.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Change_Pass;
    private javax.swing.JTextField accountID;
    private javax.swing.JTextField accountName;
    private javax.swing.JTextField accountURL;
    private javax.swing.JButton add;
    private javax.swing.JButton cancel1;
    private javax.swing.JCheckBox checkbox;
    private javax.swing.JButton edit;
    private javax.swing.JTextField filterTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenuItem jExit;
    private javax.swing.JButton jHelp;
    public javax.swing.JPanel jHomePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton jLaunch;
    private javax.swing.JMenuItem jLock;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    public javax.swing.JPanel jPanel4;
    private javax.swing.JButton jPass;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton jSetting;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jUser;
    private javax.swing.JPasswordField passwordField;
    // End of variables declaration//GEN-END:variables
}
