/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package upm;

import java.awt.Color;
import javax.swing.ButtonGroup;

/**
 *
 * @author Kai_Tang
 */
public class settingPage extends javax.swing.JFrame {

    /**
     * Creates new form settingPage
     */
    public settingPage() {
        initComponents();
        
        ButtonGroup btnG = new ButtonGroup();
        btnG.add(jDark);
        btnG.add(jWhite);
        btnG.add(jGrey);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jToggleButton1 = new javax.swing.JToggleButton();
        jDialog1 = new javax.swing.JDialog();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jSettingPanel = new javax.swing.JPanel();
        jLanguage = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jCheckBox1 = new javax.swing.JCheckBox();
        jTextField1 = new javax.swing.JTextField();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jDark = new javax.swing.JRadioButton();
        jWhite = new javax.swing.JRadioButton();
        jGrey = new javax.swing.JRadioButton();
        jCancel = new javax.swing.JButton();
        jOK = new javax.swing.JButton();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenuItem1.setText("jMenuItem1");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jToggleButton1.setText("jToggleButton1");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSettingPanel.setBackground(new java.awt.Color(255, 255, 255));
        jSettingPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLanguage.setText("Language");
        jSettingPanel.add(jLanguage, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 36, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "English (English)", "French (français)", "German (Deutsche)", "Italiano (Italiano)", "Spanish (Español)", "Dutch (Nederlands)", "Polish (Polskie)", "Greek (Ελληνικά)" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jSettingPanel.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 58, 404, -1));

        jCheckBox1.setText("Lock when out of focues (minutes)");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jSettingPanel.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 114, 272, -1));

        jTextField1.setText("1");
        jSettingPanel.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 113, 60, -1));

        jCheckBox2.setText("Keep application windows always on top");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        jSettingPanel.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 187, -1, -1));

        jCheckBox3.setText("Remember Windows position and size");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        jSettingPanel.add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 151, 272, -1));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel1.setText("Change Background");
        jSettingPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 232, -1, 31));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSettingPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 216, 428, 10));

        jDark.setText("Dark Theme");
        jDark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDarkActionPerformed(evt);
            }
        });
        jSettingPanel.add(jDark, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, -1, -1));

        jWhite.setText("White Theme");
        jWhite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jWhiteActionPerformed(evt);
            }
        });
        jSettingPanel.add(jWhite, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, -1, -1));

        jGrey.setText("Grey Theme");
        jGrey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGreyActionPerformed(evt);
            }
        });
        jSettingPanel.add(jGrey, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, -1, -1));

        jCancel.setBackground(new java.awt.Color(255, 255, 255));
        jCancel.setText("Cancel");
        jCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelActionPerformed(evt);
            }
        });
        jSettingPanel.add(jCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 76, 39));

        jOK.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        jOK.setText("OK");
        jOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOKActionPerformed(evt);
            }
        });
        jSettingPanel.add(jOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 80, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSettingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSettingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jCancelActionPerformed

    private void jDarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDarkActionPerformed
        // TODO add your handling code here:
        jSettingPanel.setBackground(new Color(38,38,38));
    }//GEN-LAST:event_jDarkActionPerformed

    private void jGreyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGreyActionPerformed
        // TODO add your handling code here:
        jSettingPanel.setBackground(new Color(128,128,128));
    }//GEN-LAST:event_jGreyActionPerformed

    private void jWhiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jWhiteActionPerformed
        // TODO add your handling code here:
        jSettingPanel.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_jWhiteActionPerformed

    private void jOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOKActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jOKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(settingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(settingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(settingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(settingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new settingPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton jCancel;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JRadioButton jDark;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JRadioButton jGrey;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLanguage;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JButton jOK;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel jSettingPanel;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JRadioButton jWhite;
    // End of variables declaration//GEN-END:variables
}
